services:
  db_flyway:
    image: flyway/flyway:10.4
    container_name: db_flyway
    # yamllint disable rule:line-length
    command: |
      -url=jdbc:postgresql://db_server/albums?allowPublicKeyRetrieval=true \
        -schemas=public \
        -user=postgres -password=root -connectRetries=60 \
        -connectRetriesInterval=2 migrate
    # yamllint enable rule:line-length
    volumes:
      - ./data/migration:/flyway/sql
    depends_on:
      - db_server

  db_server:
    # Currently Cloud SQL default postgres version is 15
    # https://cloud.google.com/sql/docs/postgres/db-versions
    image: postgres:15
    container_name: db_server
    restart: always
    volumes:
      - local_dbserver_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: postgres
      POSTGRES_DB: albums
    ports:
      - "6543:5432"
  
  app_server:
    container_name: app_server
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "6080:8080"
    environment:
      - APP_ENV=docker
    depends_on:
      - db_server
    volumes:
      - ./:/app
      - /tmp:/go/pkg/mod

  # grafana:
  #   image: grafana/grafana
  #   container_name: grafana
  #   ports:
  #     - 3000:3000
  #   restart: unless-stopped
  #   environment:
  #     - GF_SECURITY_ADMIN_USER=admin
  #     - GF_SECURITY_ADMIN_PASSWORD=admin@123
    # volumes:
    #   - ./grafana:/etc/grafana/provisioning/datasources
volumes:
  local_dbserver_data: